climbingroots/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('crags.urls')),
    path('admin/', admin.site.urls),
    path('climbers/', include('climbers.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

crags/urls.py
from django.urls import path

from . import views

app_name = 'crags'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('crags/', views.IndexCragView.as_view(), name='crags_index'),
    path('crags/cragForm', views.add_crag_view, name='crag_create'),
    path('crags/<int:pk>/', views.DetailCragView.as_view(), name='crag_detail'),
    path('crags/<int:pk_crag>/routeForm/', views.add_route_view, name='route_create'),
    path('crags/<int:pk_crag>/routes/<int:pk>/', views.IndexRouteView.as_view(), name='route_detail'),
    path('stories/', views.IndexAnecdoteView.as_view(), name='anecdote_index'),
    path('anecdote/<int:pk>/', views.DetailAnecdoteView.as_view(), name='anecdote_detail'),
    path('name_story/<int:pk>/', views.DetailNameStoryView.as_view(), name='name_story_detail'),
    path('crags/<int:pk_crag>/routes/<int:pk_route>/anecdoteForm/', views.add_anecdote_view, name='anecdote_create'),
    path('crags/<int:pk_crag>/routes/<int:pk_route>/nameStoryForm/', views.add_name_story_view, name='name_story_create'),
]

crags/models.py
from django.db import models
from crags.enums import RouteType, Grade
from django_countries.fields import CountryField


class Crag(models.Model):
    country = CountryField()
    name = models.CharField(max_length=500)
    lon = models.FloatField
    lat = models.FloatField
    address = models.CharField(max_length=500)
    isValidated = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Route(models.Model):
    crag = models.ForeignKey(Crag, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    type = models.CharField(max_length=255, choices=RouteType.choices())
    openIn = models.DateField()
    faIn = models.DateField()
    description = models.CharField(max_length=5000)
    isValidated = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Anecdote(models.Model):
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    anecdote = models.TextField()
    source = models.CharField(max_length=500)
    isValidated = models.BooleanField(default=False)

    def __str__(self):
        return self.route.name


class NameStory(models.Model):
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    story = models.TextField()
    source = models.CharField(max_length=500)
    isValidated = models.BooleanField(default=False)

    def __str__(self):
        return self.route.name

crags/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
from .models import Crag, Route, NameStory, Anecdote
from crags.enums import RouteType, Grade
from django_countries.fields import CountryField
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _

class HomeView(generic.TemplateView):
    template_name = 'crags/home.html'


class IndexCragView(generic.ListView):
    model = Crag
    template_name = 'crags/crag_index.html'


class DetailCragView(generic.DetailView):
    model = Crag
    template_name = 'crags/crag_detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        #crag = Crag.objects.get(id=self.kwargs.get('pk', ''))
        # Add in a QuerySet of all the books
        context['route_list'] = self.object.route_set.all()
        return context


class IndexRouteView(generic.DetailView):
    model = Route
    template_name = 'crags/route_detail.html'


class ResultsCragView(generic.DetailView):
    model = Crag
    template_name = 'crags/detail.html'


class IndexAnecdoteView(generic.ListView):
    model = Anecdote
    template_name = 'crags/index.html'
    context_object_name = 'anecdote_list'
    paginate_by = 15


class DetailAnecdoteView(generic.DetailView):
    model = Anecdote


class DetailNameStoryView(generic.DetailView):
    model = NameStory
#   template_name = 'stories/name_story_detail.html'


class AnecdoteForm(forms.Form):
    anecdote = forms.CharField(label=_("Anecdote"), max_length=5000, widget=forms.Textarea)
    source = forms.CharField(label=_("Source"), max_length=500)


class NameStoryForm(forms.Form):
    story = forms.CharField(label=_("Story"), max_length=5000, widget=forms.Textarea)
    source = forms.CharField(label=_("Source"), max_length=500)


class CragForm(forms.Form):
    name = forms.CharField(label=_("Name"), max_length=500)
    country = CountryField().formfield()


class RouteForm(forms.Form):
    name = forms.CharField(label=_("Name"), max_length=500)
    type = forms.ChoiceField(label=_("Type"), choices=RouteType.choices())
    description = forms.CharField(label=_("Description"), max_length=5000, widget=forms.Textarea)
    openIn = forms.DateField(label=_("Opening date"), widget=forms.SelectDateWidget)
    faIn = forms.DateField(label=_("First ascent date"), widget=forms.SelectDateWidget)


@login_required
def add_anecdote_view(request, pk_crag, pk_route):
    route = get_object_or_404(Route, pk=pk_route)
    if request.method == 'POST':
        form = AnecdoteForm(request.POST)
        if form.is_valid():
            a = Anecdote(route=route, anecdote=form.cleaned_data['anecdote'],
                         source=form.cleaned_data['source'], isValidated=False)
            a.save()
            return HttpResponseRedirect(reverse('crags:route_detail', args=[pk_crag, pk_route]))

    else:
        form = AnecdoteForm()

    return render(request, 'crags/anecdote_create.html', {'form': form, 'route': route})


@login_required
def add_name_story_view(request, pk_crag, pk_route):
    route = get_object_or_404(Route, pk=pk_route)
    if request.method == 'POST':
        form = NameStoryForm(request.POST)
        if form.is_valid():
            n = NameStory(route=route, story=form.cleaned_data['story'],
                          source=form.cleaned_data['source'], isValidated=False)
            n.save()
            return HttpResponseRedirect(reverse('crags:route_detail', args=[pk_crag, pk_route]))

    else:
        form = NameStoryForm()

    return render(request, 'crags/name_story_create.html', {'form': form, 'route': route})


@login_required
def add_crag_view(request):
    if request.method == 'POST':
        form = CragForm(request.POST)
        if form.is_valid():
            n = Crag(name=form.cleaned_data['name'], country=form.cleaned_data['country'], isValidated=False)
            n.save()
            return HttpResponseRedirect(reverse('crags:crags_index'))

    else:
        form = CragForm()

    return render(request, 'crags/crag_create.html', {'form': form})


@login_required
def add_route_view(request, pk_crag):
    crag = get_object_or_404(Crag, pk=pk_crag)
    if request.method == 'POST':
        form = RouteForm(request.POST)
        if form.is_valid():
            n = Route(name=form.cleaned_data['name'], crag=crag, type=form.cleaned_data['type'],
                      openIn=form.cleaned_data['openIn'], description=form.cleaned_data['description'],
                      faIn=form.cleaned_data['faIn'], isValidated=False)
            n.save()
            return HttpResponseRedirect(reverse('crags:route_detail', args=[pk_crag, n.id]))

    else:
        form = RouteForm()

    return render(request, 'crags/route_create.html', {'form': form, 'crag': crag})

crags/templates/crags/anecdote_create.html
{% load i18n %}

{% extends "crags/base.html" %}

{% block title %}{{ route.name|title }}{% endblock %}

{% block content %}
    <section class="wrapper style1 align-center fullscreen">
        <div class="inner">
            <h2>{% trans "New anecdote" %}</h2>
            <p>{% trans "Creation of new anecdote for the route" %}<em>{{ route.name|title }}</em></p>
            <div class="index align-left">
                <section>
                    <div class="content">
                        <form method="post" action="{% url 'crags:anecdote_create' route.crag_id route.id %}">
                            <div class="fields">
                            {% csrf_token %}
                            {{ form }}
                            </div>
                            <p class="major">{% trans "Attention your anecdote will not be visible on the site before verification" %}</p>
                            <ul class="actions"><input type="submit" value="Ajouter"></ul>
                        </form>
                    </div>
                </section>
            </div>
        </div>
    </section>
{% endblock %}

crags/templates/crags/anecdote_detail.html
<h1>{{ anecdote.anecdote }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

</form>

crags/templates/crags/crag_create.html
{% extends "crags/base.html" %}

{% block title %}Nouvelle falaise{% endblock %}

{% block content %}
<section class="wrapper style1 align-center fullscreen">
    <div class="inner">
        <h2>Nouvelle falaise</h2>
        <p>Création d'une nouvelle falaise</p>
        <div class="index align-left">
            <section>
                <div class="content">
                    <form method="post" action="{% url 'crags:crag_create' %}">
                        <div class="fields">
                        {% csrf_token %}
                        {{ form }}
                        </div>
                        <p class="major">Attention votre falaise ne sera pas visible sur le site avant vérification</p>
                        <ul class="actions"><input type="submit" value="Ajouter"></ul>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
{% endblock %}

crags/templates/crags/crag_detail.html
{% extends "crags/base.html" %}

{% block title %}{{ crag.name|title }}{% endblock %}

{% block content %}
<section class="banner style1 orient-left content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-right">
    <div class="content">
        <h1>{{ crag.name|title }}</h1>
        {% load static %}
        <p class="major"><img src="{% static crag.country.flag %}" alt="" />  {{ crag.country.name|title }}</p>
        <ul class="actions stacked">
            <li><a href="#story" class="button big wide smooth-scroll-middle">Histoire</a></li>
            <li><a href="#anecdote" class="button big wide smooth-scroll-middle">Anecdote</a></li>
            <li><a href="#routes" class="button big wide smooth-scroll-middle">Liste des voies</a></li>
        </ul>
    </div>
    <div class="image">
        {% load static %}
        <img src="{% static 'crags/images/banner.jpg' %}" alt="" />
    </div>
</section>

<section class="spotlight style1 orient-right content-align-left image-position-center onscroll-image-fade-in" id="story">
    <div class="content">
        <h2>Histoire de la falaise</h2>
        <p></p>
        <ul class="actions stacked">
            <li><a href="#" class="button">Learn More</a></li>
        </ul>
    </div>
    <div class="image">
        {% load static %}
        <img src="{% static 'crags/images/spotlight01.jpg' %}" alt="" />
    </div>
</section>

<section class="spotlight style1 orient-left content-align-left image-position-center onscroll-image-fade-in" id="anecdote">
    <div class="content">
        <h2>Anecdote</h2>
        <p></p>
        <ul class="actions stacked">
            <li><a href="#" class="button">Learn More</a></li>
        </ul>
    </div>
    <div class="image">
        {% load static %}
        <img src="{% static 'crags/images/spotlight02.jpg' %}" alt="" />
    </div>
</section>

<section class="wrapper style1 fullscreen" id="routes">
    <div class="inner">
        <h2 class="align-center">Liste des voies</h2>
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th></th>
                        <th>Nombre de voies</th>
                    </tr>
                </thead>
                <tbody>
                    {% for route in crag.route_set.all %}
                        <tr data-href="{% url 'crags:route_detail' crag.id route.id %}" >
                            <td>{{ route.name|title }}</td>
                            <td></td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2"></td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
            <a href="{% url 'crags:route_create' crag.id %}" class="button">Ajouter une voie</a>
        </div>
    </div>
</section>
{% endblock %}

crags/templates/crags/crag_detail_old.html
<h1>{{ crag.name }}</h1>
<h3>{{ crag.address }}</h3>

{% if route_list %}
    <table id="routes">
        {% for route in route_list %}
            <tr>
                <td>{{ route.name }}</td>
                <td><a href="{% url 'crags:route_detail' crag.id route.id %}">detail</a></td>
            </tr>
        {% endfor %}
    </table>
    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/climbers?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/climbers?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% else %}
    <p>No routes found!!! :(</p>
{% endif %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

crags/templates/crags/crag_index.html
{% extends "crags/base.html" %}

{% block title %}Falaises{% endblock %}

{% block content %}
<section class="wrapper style1 fullscreen">
    <div class="inner">
        <h2 class="align-center">Liste des falaises</h2>
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Pays</th>
                        <th>Nombre de voies</th>
                    </tr>
                </thead>
                <tbody>
                    {% for crag in crag_list %}
                        <tr data-href="{% url 'crags:crag_detail' crag.id %}" >
                            <td>{{ crag.name|title }}</td>
                            {% load static %}
                            <td><img src="{% static crag.country.flag %}" alt="" />  {{ crag.country.name|title }}</td>
                            <td>{{ crag.route_set.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2"></td>
                        <td><a href="{% url 'crags:crag_create' %}" class="button">Ajouter une falaise</a></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</section>
{% endblock %}

crags/templates/crags/name_story_create.html
{% extends "crags/base.html" %}

{% block title %}{{ route.name|title }}{% endblock %}

{% block content %}
<section class="wrapper style1 align-center fullscreen">
    <div class="inner">
        <h2>Nouvelle histoire</h2>
        <p>Création d'une nouvelle histoire pour la voie <em>{{ route.name|title }}</em></p>
        <div class="index align-left">
            <section>
                <div class="content">
                    <form method="post" action="{% url 'crags:name_story_create' route.crag_id route.id %}">
                        <div class="fields">
                        {% csrf_token %}
                        {{ form }}
                        </div>
                        <p class="major">Attention votre histoire ne sera pas visible sur le site avant vérification</p>
                        <ul class="actions"><input type="submit" value="Ajouter"></ul>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
{% endblock %}

crags/templates/crags/namestory_detail.html
<h1>{{ namestory.story }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

</form>

crags/templates/crags/route_create.html
{% extends "crags/base.html" %}

{% block title %}Nouvelle voie{% endblock %}

{% block content %}
<section class="wrapper style1 align-center fullscreen">
    <div class="inner">
        <h2>Nouvelle Voie</h2>
        <p>Ajout d'une voie de la falaise {{ crag.name|title }}</p>
        <div class="index align-left">
            <section>
                <div class="content">
                    <form method="post" action="{% url 'crags:route_create' crag.id %}">
                        <div class="fields">
                        {% csrf_token %}
                        {{ form }}
                        </div>
                        <p class="major">Attention votre voie ne sera pas visible sur le site avant vérification</p>
                        <ul class="actions"><input type="submit" value="Ajouter"></ul>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
{% endblock %}

crags/templates/crags/route_detail.html
{% extends "crags/base.html" %}

{% block title %}{{ route.name|title }}{% endblock %}

{% block content %}
<section class="banner style1 orient-left content-align-left image-position-left fullscreen onload-image-fade-in onload-content-fade-right">
    <div class="content">
        <header>
            <h1>{{ route.name|title }}</h1>
            <p>{{ route.crag.name|title }}</p>
        </header>
        <ul class="actions stacked">
            <li><a href="#description" class="button big wide smooth-scroll-middle">Description</a></li>
        </ul>
        <ul class="actions stacked">
            <li><a href="#nameStory" class="button big wide smooth-scroll-middle">Histoire du nom</a></li>
        </ul>
        <ul class="actions stacked">
            <li><a href="#anecdote" class="button big wide smooth-scroll-middle">Anecdote</a></li>
        </ul>
    </div>
    <div class="image">
        {% load static %}
        <img src="{% static 'crags/images/banner.jpg' %}" alt="" />
    </div>
</section>

<!-- Two -->
<section class="spotlight style1 orient-right content-align-left image-position-center onscroll-image-fade-in onscroll-content-fade-left" id="description">
    <div class="content">
        <h2>Description</h2>
        {% if route.description %}
            <p>{{ route.description }}</p>
            <ul class="actions stacked">
                <li><a href="#" class="button">Modifier</a></li>
            </ul>
        {% else %}
            <p>Aucune description de la voie n'est disponible</p>
            <ul class="actions stacked">
                <li><a href="#" class="button">Ajouter une description</a></li>
            </ul>
        {% endif %}
    </div>
    <div class="image">
        {% load static %}
        <img src="{% static 'crags/images/spotlight01.jpg' %}" alt="" />
    </div>
</section>

<!-- Three -->
<section class="spotlight style1 orient-left content-align-left image-position-center onscroll-image-fade-in onscroll-content-fade-right" id="nameStory">
    <div class="content">
        <h2>Histoires du nom</h2>
        {% if route.namestory_set %}
            {% for name_story in route.namestory_set.all %}
                {% if name_story.isValidated %}
                    <div class="box">
                        <p>{{ name_story.story }}</p>
                        <h4>Source</h4>
                        <blockquote>{{ name_story.source }}</blockquote>
                        <!--<a href="{% url 'crags:name_story_detail' name_story.id %}" class="button">Details</a>-->
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <p>Aucune histoire n'est disponible pour cette voie</p>
        {% endif %}
        <ul class="actions stacked">
            <li><a href="{% url 'crags:name_story_create' route.crag_id route.id %}" class="button">Ajouter une histoire</a></li>
        </ul>
    </div>
    <div class="image">
        {% load static %}
        <img src="{% static 'crags/images/spotlight02.jpg' %}" alt="" />
    </div>
</section>

<!-- Four -->
<section class="spotlight style1 orient-right content-align-left image-position-center onscroll-image-fade-in onscroll-content-fade-left" id="anecdote">
    <div class="content">
        <h2>Anecdotes</h2>
        {% if route.anecdote_set %}
            {% for anecdote in route.anecdote_set.all %}
                {% if anecdote.isValidated %}
                    <div class="box">
                        <p>{{ anecdote.anecdote }}</p>
                        <h4>Source</h4>
                        <blockquote>{{ anecdote.source }}</blockquote>
                        <!--<a href="{% url 'crags:name_story_detail' anecdote.id %}" class="button">Details</a>-->
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <p>Aucune anecdote n'est disponible pour cette voie</p>
        {% endif %}
        <ul class="actions stacked">
            <li><a href="{% url 'crags:anecdote_create' route.crag_id route.id %}" class="button">Ajouter une anecdote</a></li>
        </ul>
    </div>
    <div class="image">
        {% load static %}
        <img src="{% static 'crags/images/spotlight03.jpg' %}" alt="" />
    </div>
</section>
{% endblock %}